export { default as AboutUs } from "./AboutUs"
export { default as ContactUs } from "./ContactUs"
export { default as Hero } from "./Hero"
export { default as Services } from "./Services"
export { default as Works } from "./Works"
